### ISSUE TITLE
有关TI的问题

### ISSUE THREAD

**Issue by hl2500** [Xinheng-He/ti_toturial#1]
您好， 感谢您的分享。可以问几个有关Amber TI的问题吗？
1. 教程里的ligand相对比较简单， 想问下如果ligand比较复杂的话，有什么方法快速准备包含2个ligand的文件吗？如果需要准备大量的分子，有推荐的自动化工具吗？
2. 有Amber计算绝对自由能的教程吗？
谢谢！

**Comment by Xinheng-He** [comment]
不同大小的ligand都是一样准备的，可以用antechamber配合薛定谔准备。简单的命令行脚本就可以。
始态不设置分子就可以了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年1月16日(周一) 中午11:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Xinheng-He/ti_toturial] 有关TI的问题 (Issue #1)




 
您好， 感谢您的分享。可以问几个有关Amber TI的问题吗？
  
教程里的ligand相对比较简单， 想问下如果ligand比较复杂的话，有什么方法快速准备包含2个ligand的文件吗？如果需要准备大量的分子，有推荐的自动化工具吗？
 
有Amber计算绝对自由能的教程吗？
 谢谢！

**Comment by hl2500** [comment]
> 好的，谢谢。可以再问下那个包含2个ligand的相同重原子的文件（lig.pdb）只能通过手动编辑吗？感觉ligand比较复杂会花很多时间。分别在2个ligand上具有相同坐标的原子需要相同的原子名吗？
